[tool.ruff]
# 排除常见忽略目录
exclude = [
    ".git", ".venv", "__pypackages__",
    "build", "dist", "node_modules"
]

# 代码风格设置（与Black保持一致）
line-length = 88
indent-width = 4
target-version = "py311"  # 默认Python 3.11

[tool.ruff.lint]
# 默认启用的规则集
select = ["E4", "E7", "E9", "F"]  # 基础pycodestyle和Pyflakes规则
ignore = []
fixable = ["ALL"]  # 所有规则都可自动修复
unfixable = []

# 允许下划线前缀的未使用变量
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# 格式化风格（与Black兼容）
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false  # 默认不格式化文档字符串中的代码示例
